baseURL: "https://data-ethics-practice.mclaibourn.org/"
languageCode: en-us
title: "Public Interest Data: Ethics and Practice"
theme: mediumish-gohugo-theme
summaryLength: 25
copyright: Michele Claibourn - All rights reserved
enableEmoji: yes
publishDir: docs
params:
  description: LPPP 5559 Spring 2022
  author:
    name: "Professor: Michele Claibourn"
    description: "(Director of Equitable Analysis, UVA Equity Center)"
    thumbnail: images/pid_hex2.png
  index:
    alertbar: no
    mdtext: |
      Wednesdays, 2:00-4:30
      
      *Dr. Michele Claibourn (Director of Equitable Analysis, UVA Equity Center and Assistant Professor in Batten)*
      
      **Email: mclaibourn@virginia.edu  |  Office Hours: By appt.  |  Office: Let's meet outside or on zoom**
    picture: images/pid_hex2.png
    subtitle: LPPP 5559 Spring 2022
    title: "Public Interest Data: Ethics and Practice"
  logo: 
  social:
    github: mclaibourn
    twitter: mclaibourn
    linkedin: mclaibourn
    mail: mclaibourn@virginia.edu

menu:
  main:
    - identifier: syllabus
      name: Syllabus
      url: /static/syllabus
      weight: 100
    - identifier: schedule
      name: Schedule
      url: /static/schedule
      weight: 200
    - identifier: resources
      name: Resources
      url: /static/resources
      weight: 500
    - identifier: slack
      name: Class Slack
      url: https://data-ethics-practice.slack.com
      weight: 600
    - identifier: policy
      name: Batten Policies
      url: /static/policy
      weight: 700

markup:
  goldmark:
    renderer:
      unsafe: true
